"""Stage 6: per-dependency tech-debt research + cross-reference check.

Reads dependency manifests, runs doer/checker loop per dep (both agents have
Perplexity + Context7 MCP access), and emits TECH_DEBT.md with one row per dep.

v1.1 incremental: hash the stable (name, pinned, source) triple set of
parsed deps. Skip the whole stage if state.rollup_hashes["tech_debt"]
matches AND TECH_DEBT.md is still on disk.
"""

from __future__ import annotations

import hashlib
import json

from designdoc.agents.tech_debt import (
    build_crossref_prompt,
    build_researcher_prompt,
    make_tech_debt_crossref,
    make_tech_debt_researcher,
)
from designdoc.index.manifests import Dep, parse_manifests
from designdoc.loop import doer_checker_loop
from designdoc.state import PipelineState, StageStatus

STAGE_NAME = "tech_debt"
OUTPUT_FILENAME = "TECH_DEBT.md"
ROLLUP_KEY = "tech_debt"


async def run(
    *,
    state: PipelineState,
    runner,
    doer_model: str = "claude-sonnet-4-6",
    checker_model: str = "claude-sonnet-4-6",
    mcp_servers: list[str] | None = None,
) -> list[dict]:
    """Execute Stage 6. Returns the list of tech-debt entries (one per dep)."""
    state.stages[STAGE_NAME] = StageStatus.RUNNING
    state.save()

    deps = parse_manifests(state.target_repo)
    input_hash = _hash_deps(deps)
    output_path = state.output_dir / OUTPUT_FILENAME

    # Skip when deps unchanged AND the ledger is still on disk.
    if state.rollup_hashes.get(ROLLUP_KEY) == input_hash and output_path.exists():
        state.stages[STAGE_NAME] = StageStatus.DONE
        state.current_stage = max(state.current_stage, 7)
        state.save()
        return []

    researcher = make_tech_debt_researcher(model=doer_model, mcp_servers=mcp_servers)
    crossref = make_tech_debt_crossref(model=checker_model, mcp_servers=mcp_servers)

    rows: list[dict] = []
    for dep in deps:
        doer_prompt = build_researcher_prompt(dep.name, dep.pinned)

        def checker_prompt_fn(research_json: str, *, _name=dep.name, _pin=dep.pinned) -> str:
            return build_crossref_prompt(_name, _pin, research_json)

        result = await doer_checker_loop(
            artifact_id=f"dep:{dep.name}",
            doer=researcher,
            checker=crossref,
            doer_prompt=doer_prompt,
            checker_prompt_fn=checker_prompt_fn,
            runner=runner,
            hil_sink=state.hil_issues,
            stage_name=STAGE_NAME,
        )

        row = _parse_report(result.text, dep, disputed=result.status != "pass")
        rows.append(row)

    output_path.write_text(_render_markdown(rows))
    state.rollup_hashes[ROLLUP_KEY] = input_hash
    state.stages[STAGE_NAME] = StageStatus.DONE
    state.current_stage = max(state.current_stage, 7)
    state.save()
    return rows


def _hash_deps(deps: list[Dep]) -> str:
    """Stable SHA1 over (name, pinned, source) sorted by name."""
    h = hashlib.sha1()
    for dep in sorted(deps, key=lambda d: d.name):
        h.update(dep.name.encode("utf-8"))
        h.update(b"\0")
        h.update(dep.pinned.encode("utf-8"))
        h.update(b"\0")
        h.update(dep.source.encode("utf-8"))
        h.update(b"\n")
    return h.hexdigest()


def _parse_report(text: str, dep, disputed: bool) -> dict:
    try:
        data = json.loads(text)
    except json.JSONDecodeError:
        data = {"name": dep.name, "pinned": dep.pinned, "status": "unknown"}
    data.setdefault("name", dep.name)
    data.setdefault("pinned", dep.pinned)
    data.setdefault("latest", "unknown")
    data.setdefault("status", "unknown")
    data.setdefault("recommended_action", "none")
    data.setdefault("sources", [])
    data["disputed"] = disputed
    data["source_file"] = dep.source
    return data


def _render_markdown(rows: list[dict]) -> str:
    header = (
        "# Tech Debt Ledger\n\n"
        "Generated by designdoc Stage 6. Each row reflects a researcher + cross-ref\n"
        "checker pair; disputed rows are flagged in the Notes column.\n\n"
        "| Dep | Pinned | Latest | Status | Action | Source | Notes |\n"
        "|---|---|---|---|---|---|---|\n"
    )
    body = "\n".join(
        "| {name} | {pinned} | {latest} | {status} | {action} | {source_file} | {notes} |".format(
            name=r["name"],
            pinned=r["pinned"] or "-",
            latest=r["latest"],
            status=r["status"],
            action=r["recommended_action"],
            source_file=r["source_file"],
            notes=("DISPUTED — see hil-issues.yaml" if r.get("disputed") else ""),
        )
        for r in rows
    )
    return header + body + "\n"
