"""Stage 8: write README.md TOC and emit hil-issues.yaml.

Deterministic. No LLM. Walks the output tree, builds a nested-bullet TOC
linking every generated artifact, and appends any accumulated HIL issues to
hil-issues.yaml. Safe to re-run on the same directory.
"""

from __future__ import annotations

import json
from pathlib import Path

from designdoc.hil import HILIssue, append_issue
from designdoc.stages.s0_discover import OUTPUT_FILENAME as STAGE0_FILENAME
from designdoc.state import PipelineState, StageStatus

STAGE_NAME = "finalize"
README_FILENAME = "README.md"
HIL_FILENAME = "hil-issues.yaml"


async def run(*, state: PipelineState) -> dict[str, str]:
    """Execute Stage 8. Returns {'readme': rel_path, 'hil': rel_path_or_empty}."""
    output = state.output_dir
    output.mkdir(parents=True, exist_ok=True)

    state.stages[STAGE_NAME] = StageStatus.RUNNING
    state.save()

    readme_path = output / README_FILENAME
    readme_path.write_text(_render_toc(output))

    # Emit HIL YAML iff any issues accumulated during the run
    hil_path = output / HIL_FILENAME
    for issue in state.hil_issues:
        append_issue(hil_path, _to_hil_issue(issue))

    # Promote Stage 0's hashes into prev_hashes so the NEXT run has a
    # baseline to diff against for incremental regeneration.
    _promote_current_hashes(state, output)

    state.stages[STAGE_NAME] = StageStatus.DONE
    state.current_stage = max(state.current_stage, 9)
    state.save()
    return {
        "readme": str(readme_path.relative_to(output)),
        "hil": str(hil_path.relative_to(output)) if hil_path.exists() else "",
    }


def _promote_current_hashes(state: PipelineState, output: Path) -> None:
    """Copy the current run's Stage 0 hashes into state.prev_hashes.

    No-op if Stage 0 didn't run (incremental-only pipelines, or test
    harnesses that invoke Stage 8 in isolation).
    """
    stage0_path = output / STAGE0_FILENAME
    if not stage0_path.exists():
        return
    data = json.loads(stage0_path.read_text())
    hashes = data.get("hashes") or {}
    if hashes:
        state.prev_hashes = dict(hashes)


def _to_hil_issue(raw: dict) -> HILIssue:
    return HILIssue(
        id=raw["id"],
        artifact=raw["artifact"],
        stage=raw["stage"],
        severity=raw["severity"],
        doer_said=raw.get("doer_said", ""),
        checker_said=raw.get("checker_said", ""),
        attempts=raw.get("attempts", 3),
        status=raw.get("status", "open"),
        suggested_fixes=raw.get("suggested_fixes", []),
        source_file=raw.get("source_file"),
        category=raw.get("category"),
    )


def _render_toc(output: Path) -> str:
    lines = ["# Design Documentation\n"]
    lines.append("Generated by designdoc. Entry points:\n")
    if (output / "SYSTEM_DESIGN.md").exists():
        lines.append("- [System Design](SYSTEM_DESIGN.md)")
    if (output / "ARCHITECTURE.md").exists():
        lines.append("- [Architecture](ARCHITECTURE.md)")
    if (output / "TECH_DEBT.md").exists():
        lines.append("- [Tech Debt Ledger](TECH_DEBT.md)")
    if (output / HIL_FILENAME).exists():
        lines.append("- [Unresolved HIL issues](hil-issues.yaml)")

    packages_dir = output / "packages"
    if packages_dir.exists():
        lines.append("\n## Packages\n")
        for pkg in sorted(p for p in packages_dir.iterdir() if p.is_dir()):
            pkg_readme = pkg / "README.md"
            if pkg_readme.exists():
                lines.append(f"- [{pkg.name}](packages/{pkg.name}/README.md)")
            classes = sorted((pkg / "classes").glob("*.md")) if (pkg / "classes").exists() else []
            for cls in classes:
                lines.append(f"  - [{cls.stem}](packages/{pkg.name}/classes/{cls.name})")
    return "\n".join(lines) + "\n"
